Repository syslaudo/syslaudo-frontend, pull requests merged in 2021-05, with the labels that each got.

#7 Crud frontend
  .env
  README.md
  db.json
  package.json
  src/App.tsx
  src/components/Body/styles.ts
  src/components/Can/index.tsx
  src/components/FormComponents/RadioButton/styles.ts
  src/components/FormComponents/RadioGroup/styles.ts
  src/components/Header/DesktopNavbar/styles.ts
  src/components/Header/MobileNavbar/styles.ts
  src/components/Header/Navlinks/index.tsx
  src/components/Header/ProfileSubmenu/index.tsx
  src/components/Header/index.tsx
  src/components/Table/index.tsx
  src/components/Tabs/index.tsx
  src/components/Tabs/styles.ts
  src/hooks/useCan.tsx
  src/hooks/useExams.tsx
  src/hooks/usePatients.tsx
  src/hooks/useUsers.tsx
  src/index.tsx
  src/pages/Doctors/DoctorForm/index.tsx
  src/pages/Doctors/DoctorUpdateModal/index.tsx
  src/pages/Doctors/index.tsx
  src/pages/Exams/CanceledExams/index.tsx
  src/pages/Exams/CanceledExams/styles.ts
  src/pages/Exams/ExamRequestForm/index.tsx
  src/pages/Exams/ExamViewModal/index.tsx
  src/pages/Exams/ExamViewModal/styles.ts
  src/pages/Exams/PendingReport/index.tsx
  src/pages/Exams/PendingReport/styles.ts
  src/pages/Exams/ScheduledExams/ExamFulfillForm/index.tsx
  src/pages/Exams/ScheduledExams/ExamFulfillModal/index.tsx
  src/pages/Exams/ScheduledExams/ExamRequestCreateModal/index.tsx
  src/pages/Exams/ScheduledExams/ExamRequestForm/index.tsx
  src/pages/Exams/ScheduledExams/ExamRequestUpdateModal/index.tsx
  src/pages/Exams/ScheduledExams/index.tsx
  src/pages/Exams/ScheduledExams/styles.ts
  src/pages/Exams/index.tsx
  src/pages/Exams/styles.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/pages/Login/index.tsx
  src/pages/Login/styles.ts
  src/pages/Patients/PatientForm/index.tsx
  src/pages/Patients/PatientUpdateModal/index.tsx
  src/pages/Patients/index.tsx
  src/pages/Users/UserForm/index.tsx
  src/pages/Users/UserPasswordUpdateForm/index.tsx
  src/pages/Users/UserUpdateModal/index.tsx
  src/pages/Users/index.tsx
  src/services/Auth.ts
  src/services/api.ts
  src/services/auth.ts
  src/styles/global.ts
  tsconfig.json
  yarn.lock
Labels: bug, duplicate

#11 BDD aplicado à tela de login
  tests/browser.py
  tests/environment.py
  tests/features/login.feature
  tests/model/syslaudo.py
  tests/pages/syslaudo_pages.py
  tests/requirements.txt
  tests/results/login-result.txt
  tests/steps/steps.py
Labels: documentation, enhancement, help wanted, wontfix

#12 Refatoração de datas e CPFs e melhora nas mensagens de erro
  .env
  db.json
  src/components/FormComponents/MultilineInput/index.tsx
  src/components/FormComponents/RadioButton/index.tsx
  src/components/FormComponents/Select/index.tsx
  src/components/Header/DesktopNavbar/index.tsx
  src/components/Header/DesktopNavbar/styles.ts
  src/components/Header/MobileNavbar/index.tsx
  src/components/Header/MobileNavbar/styles.ts
  src/pages/Doctors/DoctorForm/index.tsx
  src/pages/Doctors/index.tsx
  src/pages/Exams/CanceledExams/index.tsx
  src/pages/Exams/ExamViewModal/index.tsx
  src/pages/Exams/ExamViewModal/styles.ts
  src/pages/Exams/PendingReport/index.tsx
  src/pages/Exams/ScheduledExams/ExamFulfillForm/index.tsx
  src/pages/Exams/ScheduledExams/ExamRequestForm/index.tsx
  src/pages/Exams/ScheduledExams/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/Login/styles.ts
  src/pages/Patients/PatientForm/index.tsx
  src/pages/Patients/index.tsx
  src/pages/Users/UserForm/index.tsx
  src/pages/Users/UserPasswordUpdateForm/index.tsx
Labels: bug, enhancement, help wanted
